***************
*** 60,66 ****
  
  
  # MCU name
- MCU = at90usb1287
  
  
  # Target architecture (see library "Board Types" documentation).
--- 60,66 ----
  
  
  # MCU name
+ MCU = atmega32u2
  
  
  # Target architecture (see library "Board Types" documentation).
***************
*** 70,76 ****
  # Target board (see library "Board Types" documentation, NONE for projects not requiring
  # LUFA board drivers). If USER is selected, put custom board drivers in a directory called
  # "Board" inside the application directory.
- BOARD = USBKEY
  
  
  # Processor frequency.
--- 70,76 ----
  # Target board (see library "Board Types" documentation, NONE for projects not requiring
  # LUFA board drivers). If USER is selected, put custom board drivers in a directory called
  # "Board" inside the application directory.
+ BOARD = MINIMUS
  
  
  # Processor frequency.
***************
*** 84,90 ****
  #     does not *change* the processor frequency - it should merely be updated to
  #     reflect the processor speed set externally so that the code can use accurate
  #     software delays.
- F_CPU = 8000000
  
  
  # Input clock frequency.
--- 84,90 ----
  #     does not *change* the processor frequency - it should merely be updated to
  #     reflect the processor speed set externally so that the code can use accurate
  #     software delays.
+ F_CPU = 16000000
  
  
  # Input clock frequency.
